// Mocks generated by Mockito 5.4.6 from annotations
// in zergo_frontend/test/features/diner/enhanced_menu_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:zergo_frontend/features/diner/application/services/cart_service.dart'
    as _i8;
import 'package:zergo_frontend/features/diner/application/use_cases/fetch_menu.dart'
    as _i3;
import 'package:zergo_frontend/features/diner/domain/entities/menu_item.dart'
    as _i7;
import 'package:zergo_frontend/features/diner/domain/entities/menu_structure.dart'
    as _i5;
import 'package:zergo_frontend/features/diner/domain/entities/restaurant_branding.dart'
    as _i6;
import 'package:zergo_frontend/features/diner/domain/entities/search_result.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMenuSearchResult_0 extends _i1.SmartFake
    implements _i2.MenuSearchResult {
  _FakeMenuSearchResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchMenuUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchMenuUseCase extends _i1.Mock implements _i3.FetchMenuUseCase {
  MockFetchMenuUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.MenuStructure?> getMenuStructure(String? restaurantCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuStructure,
          [restaurantCode],
        ),
        returnValue: _i4.Future<_i5.MenuStructure?>.value(),
      ) as _i4.Future<_i5.MenuStructure?>);

  @override
  _i4.Future<_i6.RestaurantBranding?> getRestaurantBranding(
          String? restaurantCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantBranding,
          [restaurantCode],
        ),
        returnValue: _i4.Future<_i6.RestaurantBranding?>.value(),
      ) as _i4.Future<_i6.RestaurantBranding?>);

  @override
  _i4.Future<_i2.MenuSearchResult> searchMenuItems(
    String? restaurantCode,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMenuItems,
          [
            restaurantCode,
            query,
          ],
        ),
        returnValue:
            _i4.Future<_i2.MenuSearchResult>.value(_FakeMenuSearchResult_0(
          this,
          Invocation.method(
            #searchMenuItems,
            [
              restaurantCode,
              query,
            ],
          ),
        )),
      ) as _i4.Future<_i2.MenuSearchResult>);

  @override
  _i4.Future<List<_i7.DinerMenuItem>> getFeaturedItems(
          String? restaurantCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedItems,
          [restaurantCode],
        ),
        returnValue:
            _i4.Future<List<_i7.DinerMenuItem>>.value(<_i7.DinerMenuItem>[]),
      ) as _i4.Future<List<_i7.DinerMenuItem>>);

  @override
  _i4.Future<List<_i7.DinerMenuItem>> call(String? restaurantCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [restaurantCode],
        ),
        returnValue:
            _i4.Future<List<_i7.DinerMenuItem>>.value(<_i7.DinerMenuItem>[]),
      ) as _i4.Future<List<_i7.DinerMenuItem>>);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i8.CartService {
  MockCartService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getSessionToken() => (super.noSuchMethod(
        Invocation.method(
          #getSessionToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveSessionToken(
    String? token,
    String? restaurantId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionToken,
          [
            token,
            restaurantId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> createAnonymousSession({
    required String? restaurantId,
    String? tableId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAnonymousSession,
          [],
          {
            #restaurantId: restaurantId,
            #tableId: tableId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> getOrCreateSession(String? restaurantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSession,
          [restaurantId],
        ),
        returnValue: _i4.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateSession,
            [restaurantId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> addItemToCart({
    required String? sessionToken,
    required String? menuItemId,
    required int? quantity,
    Map<String, dynamic>? customizations,
    String? specialInstructions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemToCart,
          [],
          {
            #sessionToken: sessionToken,
            #menuItemId: menuItemId,
            #quantity: quantity,
            #customizations: customizations,
            #specialInstructions: specialInstructions,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateCartItem({
    required String? itemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [],
          {
            #itemId: itemId,
            #quantity: quantity,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> removeCartItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [itemId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getCartSummary(String? sessionToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartSummary,
          [sessionToken],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCartItems(String? sessionToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCartItems,
          [sessionToken],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> clearCart(String? sessionToken) => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [sessionToken],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
