version: "3.9"
services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on: []

  # Add optional services like a local postgres or supabase if needed later
networks:
  default:
    name: zergoqrf
