name: zergo_frontend
version: 0.1.0+1
description: ZERGO QR Flutter app
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  go_router: ^14.2.7
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.4
  build_runner: ^2.4.8
  golden_toolkit: ^0.15.0
  patrol: ^3.12.0

flutter:
  uses-material-design: true
  assets:
    - .env