name: backend
on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'apps/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend
        working-directory: apps/backend
        run: |
          python -m pip install -U pip
          pip install -e .
      - name: Run tests
        working-directory: apps/backend
        run: pytest -q
