name: frontend
on:
  push:
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'apps/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        working-directory: apps/frontend
        run: flutter pub get
      - name: Analyze
        working-directory: apps/frontend
        run: flutter analyze
      - name: Test
        working-directory: apps/frontend
        run: flutter test -r expanded
      - name: Build web
        working-directory: apps/frontend
        run: flutter build web --release
